#!/bin/bash
set -e
abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
scripts_dir=`dirname "$abspath"`
echo "scripts_dir $scripts_dir"

echo "Checking whether the container is running from $scripts_dir"
$scripts_dir/run-jsw status

exit $?
