#!/bin/bash
set -e
abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
scripts_dir=`dirname "$abspath"`
echo "scripts_dir $scripts_dir"

echo "Stopping container::$scripts_dir/run-jsw"
$scripts_dir/run-jsw stop

# poll until the application has stopped completely
while true;
do
   status=$(sh $scripts_dir/running | grep " is not running")
   # check if the status has a non-zero length
   if [ -z "$status" ]
   then
      echo "Application has yet stopped."
   else
      echo "Application has stopped"
      break
   fi
done


echo "Done Shutdown"
