#!/bin/bash

abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
scripts_dir=`dirname "$abspath"`
echo "scripts_dir $scripts_dir"

echo "Starting application through Java Service Wrapper $scripts_dir"

#XIA: 
echo "Calling autoconfig.sh from startup script"
$scripts_dir/autoconfig.sh
if [ $? -ne 0 ]; then
	echo "#############################[ERROR] Auto Configuration FAIL#############################"
	echo "exit startup script now";
	exit 1;
fi  

$scripts_dir/run-jsw start

echo -e "\nWaiting for application to start completely..."

# poll until the application started completely
while true;
do
   status=$(sh $scripts_dir/running | grep " is running: ")
   # check if the status has a non-zero length
   if [ -z "$status" ]
   then
      echo "Application has yet started."
   else
      echo "Application has started!!"
      $scripts_dir/loadmeta.sh
      break
   fi
done


exit 0

